install playwright
 1) tests/example.spec.ts:4:1 › my test ===========================================================

    browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-920619/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/index.js:127:40)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:297:23)
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)

  2) tests/foo.spec.ts:3:1 › basic test ============================================================

    browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-920619/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/index.js:127:40)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:297:23)
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)

  2 failed
    tests/example.spec.ts:4:1 › my test ============================================================
    tests/foo.spec.ts:3:1 › basic test =============================================================
Error: Process completed with exit code 1.