add deps
Run yarn --version
3.0.2
6.14.15
v14.17.6
.
..
.git
.github
.gitignore
.yarn
.yarnrc.yml
package.json
tests
yarn.lock
➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
Link step
➤ YN0000: └ Completed in 2s 251ms
➤ YN0000: Done in 2s 463ms
Playwright build of chromium v920619 downloaded to /home/runner/.cache/ms-playwright/chromium-920619
Playwright build of ffmpeg v1005 downloaded to /home/runner/.cache/ms-playwright/ffmpeg-1005
Playwright build of firefox v1295 downloaded to /home/runner/.cache/ms-playwright/firefox-1295
Playwright build of webkit v1542 downloaded to /home/runner/.cache/ms-playwright/webkit-1542
/home/runner/work/playwright-test/playwright-test/tests/example.spec.ts-snapshots/get-started-linux.png is missing in snapshots, writing actual.
··

  2 passed (2s)
F·F·FF

  1) [chromium] › tests/example.spec.ts:4:1 › my test ==============================================

    Error: /home/runner/work/playwright-test/playwright-test/tests/example.spec.ts-snapshots/get-started-chromium-linux.png is missing in snapshots, writing actual.

      19 |
      20 |   // Compare screenshot with a stored reference.
    > 21 |   expect(await page.screenshot()).toMatchSnapshot('get-started.png');
         |                                   ^
      22 | });

        at /home/runner/work/playwright-test/playwright-test/tests/example.spec.ts:21:35
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)

  2) [firefox] › tests/example.spec.ts:4:1 › my test ===============================================

    Error: /home/runner/work/playwright-test/playwright-test/tests/example.spec.ts-snapshots/get-started-firefox-linux.png is missing in snapshots, writing actual.

      19 |
      20 |   // Compare screenshot with a stored reference.
    > 21 |   expect(await page.screenshot()).toMatchSnapshot('get-started.png');
         |                                   ^
      22 | });

        at /home/runner/work/playwright-test/playwright-test/tests/example.spec.ts:21:35
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)

  3) [webkit] › tests/example.spec.ts:4:1 › my test ================================================

    browserType.launch:
    ╔════════════════════════════════════════════════════════════╗
    ║ Host system is missing a few dependencies to run browsers. ║
    ║ Please install them with the following command:            ║
    ║                                                            ║
    ║     sudo npx playwright install-deps                       ║
    ║                                                            ║
    ║ <3 Playwright Team                                         ║
    ╚════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/index.js:127:40)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:297:23)
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)

  4) [webkit] › tests/foo.spec.ts:3:1 › basic test =================================================

    browserType.launch:
    ╔════════════════════════════════════════════════════════════╗
    ║ Host system is missing a few dependencies to run browsers. ║
    ║ Please install them with the following command:            ║
    ║                                                            ║
    ║     sudo npx playwright install-deps                       ║
    ║                                                            ║
    ║ <3 Playwright Team                                         ║
    ╚════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/index.js:127:40)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at Fixture.setup (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/fixtures.js:297:23)
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/playwright-test/playwright-test/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)

  4 failed
    [chromium] › tests/example.spec.ts:4:1 › my test ===============================================
    [firefox] › tests/example.spec.ts:4:1 › my test ================================================
    [webkit] › tests/example.spec.ts:4:1 › my test =================================================
    [webkit] › tests/foo.spec.ts:3:1 › basic test ==================================================
  2 passed (11s)
Error: Process completed with exit code 1.